sudo: required

services:
  - docker

before_install: 
# This was before the COPY in the dockerfile.dev commented, as I'm now using docker-compose so, no need
 - docker build -t rajatkaushik/docker-react -f Dockerfile.dev .

script:
  # - docker-compose up --build tests
 - docker run rajatkaushik/docker-react npm run test
