sudo: required

services:
  - docker

before_install: 
# This was before the COPY in the dockerfile.dev commented, as I'm now using docker-compose so, no need
 

script:
  - docker build -t rajatkaushik/docker-react .
  # - docker-compose up --build tests
#  - docker run -p 80:80 rajatkaushik/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-138422526254"
  bucket_path: "docker-react" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
